# Generated by Django 3.2.6 on 2021-08-14 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hunt.apps.users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=70)),
                ('is_student', models.BooleanField(default=False)),
                ('graduation_year', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=50)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('challenges_done', models.ManyToManyField(related_name='users_that_completed', to='main.Challenge')),
                ('hoco_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_set', to='main.class')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', hunt.apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_service', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
                ('users', models.ManyToManyField(related_name='unix_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
