# Generated by Django 3.2.6 on 2021-08-14 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='_is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hoco_class',
        ),
    ]
