# Generated by Django 3.2.6 on 2021-08-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('flag', models.CharField(max_length=50)),
                ('points', models.IntegerField()),
                ('exclusive', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(choices=[('2022', 'Seniors'), ('2023', 'Juniors'), ('2024', 'Sophomores'), ('2025', 'Freshmen')], max_length=20, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('challenges_completed', models.ManyToManyField(related_name='classes_completed', to='main.Challenge')),
            ],
        ),
    ]
