# Generated by Django 3.2.6 on 2021-08-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='challenges_completed',
            field=models.ManyToManyField(blank=True, related_name='classes_completed', to='main.Challenge'),
        ),
    ]
