# Generated by Django 3.2.7 on 2021-09-20 08:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210920_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='short_description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
