# Generated by Django 3.2.7 on 2021-09-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
