# Generated by Django 3.2.7 on 2021-09-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_challenge_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='available',
            new_name='unblocked',
        ),
    ]
