# Generated by Django 3.2.7 on 2021-09-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='flag',
            field=models.CharField(max_length=100),
        ),
    ]
